################
### SERVICES ###
################

[services.GitHub]
v2fly = ["github"]

[services.TMDB]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=themoviedb.org"
]
v2fly = ["tmdb"]

[services.HBO]
v2fly = ["hbo"]

[services.Hulu]
v2fly = ["hulu"]

[services.PrimeVideo]
v2fly = ["primevideo"]

[services.Netflix]
v2fly = ["netflix"]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=netflix.com"
]

[services.Intel]
v2fly = ["intel"]

[services.LostFilm]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=lostfilm.tv"
]

[services.RuTracker]
v2fly = ["rutracker"]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=rutracker.org"
]

[services.1337x]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=1337x.to"
]

[services.BookTracker]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=booktracker.org"
]

[services.FilmiTorrent]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=filmitorrent.net"
]

[services.Kinozal]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=kinozal.me"
]

[services.NewStudio]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=newstudio.tv"
]

[services.NNMClub]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=nnmclub.to"
]

[services.Rustorka]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=rustorka.com"
]

[services.RuTor]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=rutor.info"
]

[services.ThePirateBay]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=thepiratebay.org"
]

[services.TorrentBy]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=torrent.by"
]

[services.OpenStreetMap]
v2fly = ["openstreetmap"]

[services.OpenWeather]
v2fly = ["openweather"]

[services.Notion]
v2fly = ["notion"]
domains = ["notion-emojis.s3-us-west-2.amazonaws.com"]

[services.Miro]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=miro.com"
]

[services.Flibusta]
v2fly = ["flibusta"]

[services.Google-AI]
v2fly = ["google-deepmind", "google-gemini"]

[services.Copilot]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=copilot"
]

[services.ElevenLabs]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=elevenlabs.io"
]

[services.Telegram]
v2fly = ["telegram"]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=telegram.org"
]
general = false

[services.YouTube]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=youtube.com",
    "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Services/youtube.lst"
]
v2fly = ["youtube"]

[services.TikTok]
v2fly = ["tiktok"]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=tiktok.com"
]

[services."X"]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=x.com&site=x.com"
]
v2fly = ["twitter"]
domains = ["video.twimg.com.cdn.cloudflare.net"]

[services.Grok]
v2fly = ["xai"]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=grok.com"
]

[services.Discord]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=discord.com&site=discord.gg&site=discord.media"
]
v2fly = ["discord"]

[services.SuperCell]
v2fly = ["supercell"]

[services.DeviantArt]
v2fly = ["deviantart"]

[services.OpenAI]
v2fly = ["openai"]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=chatgpt.com"
]

[services.Anthropic]
v2fly = ["anthropic"]

[services.Oculus]
v2fly = ["oculus"]
domains = ["oculus.com"]
general = true

[services.Meta]
domains = ["meta.ai", "meta.com"]

[services.Instagram]
v2fly = ["instagram"]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=instagram.com"
]

[services.Facebook]
v2fly = ["facebook", "facebook-dev"]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=facebook.com"
]

[services.Threads]
v2fly = ["threads"]

[services.Quora]
v2fly = ["quora"]

[services.LinkedIn]
v2fly = ["linkedin"]

[services.Messenger]
v2fly = ["messenger"]

[services.Signal]
v2fly = ["signal"]

[services.WhatsApp]
v2fly = ["whatsapp"]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=whatsapp.com"
]
domains = ["fbcdn.net"]
general = true

[services.Spotify]
v2fly = ["spotify"]

[services.SoundCloud]
v2fly = ["soundcloud"]

[services.Tidal]
domains = ["tidal.com"]

[services.HDRezka]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=hdrezka.ag"
]

[services.LordFilm]
domains = [
    "lordfilm.ag", "lordfilm.app", "lordfilm.art", "lordfilm.asia",
    ...
    "lordfilm.xyz", "lordfilm.zone"
]

[services.AWS]
v2fly = ["aws"]
general = false

[services.Viber]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=viber.com"
]

[services.Twitch]
v2fly = ["twitch"]

[services.DeepSeek]
domains = ["deepseek.com"]
general = false

[services.Perplexity]
v2fly = ["perplexity"]
general = false

[services.HuggingFace]
v2fly = ["huggingface"]
general = false

[services.Doramy-club]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=doramy.club"
]

[services.filmix]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=filmix.fm"
]
domains = ["filmix.my"]

[services.kinopub]
domains = ["kino.pub"]

[services.kinobase]
domains = ["kinobase.org"]

[services.kinovod]
domains = ["kinovod.net", "kinovod.pro"]

[services.JetBrains]
v2fly = ["jetbrains", "jetbrains-ai"]

[services.BestChange]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=bestchange.ru"
]

[services.ProtonMail]
v2fly = ["protonmail"]

[services.Notepad++]
domains = ["notepad-plus-plus.org"]

[services.Sentry-io]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=sentry.io"
]

[services.DeepL]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=deepl.com"
]

[services.Canva]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=canva.com"
]

[services.10MinuteMail]
domains = ["10minutemail.com"]

[services.Strava]
domains = ["strava.com"]

[services.Zapier]
domains = ["zapier-deployment.com", "zapier.com"]

[services.Whoop]
domains = ["whoop.com"]

[services.Tuta]
domains = ["tuta.com"]

[services.AutoDesk]
v2fly = ["autodesk"]
domains = [
    "autodesk.com", "a360.co", "autodesk.io", "autodesk.net",
    "autodesk360.com", "tinkercad.com"
]
general = false

[services.SpeedTest]
v2fly = ["speedtest"]

[services.Adobe]
domains = ["omtrdc.net"]


##############
### GROUPS ###
##############

[groups.Google-ALL]
include = ["youtube"]
v2fly = ["google"]

[groups.Torrent-Trackers]
include = [
    "1337x", "booktracker", "filmitorrent", "kinozal", "newstudio",
    "nnmclub", "rustorka", "rutor", "rutracker", "thepiratebay",
    "torrentby", "flibusta", "lostfilm"
]

[groups.Streaming-Services]
include = ["netflix", "hulu", "primevideo", "hbo"]

[groups.Social]
include = [
    "discord", "telegram", "viber", "instagram", "facebook",
    "threads", "x", "tiktok", "linkedin", "messenger",
    "signal", "whatsapp"
]

[groups.AI]
include = [
    "google-ai", "elevenlabs", "copilot", "openai", "grok",
    "deepseek", "perplexity", "huggingface", "anthropic"
]
domains = ["meta.ai"]
v2fly = ["jetbrains-ai"]

[groups.RU-unblocked]
v2fly = ["category-ru", "category-gov-ru"]
url = [
    "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Russia/outside-raw.lst",
    "https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/refs/heads/master/data/category-banks-ru",
    "https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/refs/heads/master/data/category-only-ru"
]
domains = [
    "by", "xn--90ais", "2ch.life", "ru.com", "ru.net", "rt.com",
    "sputniknews.com", "sputnikglobe.com", "actualidad-rt.com",
    "africa-rt.com", "esrt.press", "estr.online", "rt-afrique.com",
    "rtafrica.media", "rtafrique.online", "tass.com", "interfax.com",
    "1c.com", "2ch.hk", "advmaker.net", "pravda.com", "news-pravda.com"
]
general = false

[groups.Music]
include = ["spotify", "soundcloud", "tidal"]

[groups.Tools]
include = [
    "jetbrains", "bestchange", "notion", "miro", "sentry-io",
    "deepl", "canva", "10minutemail", "strava", "zapier",
    "whoop", "tuta", "autodesk"
]

[groups.Porn]
v2fly = ["category-porn"]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=beeg.com&site=hqporner.com&site=pornhub.com&site=pornolab.net&site=reddxxx.com&site=redgifs.com&site=redtube.com&site=rule34.xxx&site=xhamster.com&site=xhamsterlive.com&site=xnxx-ru.com&site=xvideos.com"
]
general = false

[groups.Meta-All]
v2fly = ["meta"]
general = false

[groups.Ads]
v2fly = ["category-ads-all"]
domains = ["ad.cub.red"]
general = false

[groups.RU-Media]
url = [
    "https://iplist.opencck.org/?format=text&data=domains&site=agents.media&site=agentura.ru&site=bbc.com&site=bellingcat.com&site=cherta.media&site=colta.ru&site=currenttime.tv&site=dept.one&site=doxa.team&site=dw.com&site=echofm.online&site=ehorussia.com&site=ej.ru&site=euronews.com&site=exler.ru&site=golosameriki.com&site=gordonua.com&site=gulagu.net&site=holod.media&site=hrw.org&site=istories.media&site=kasparov.ru&site=kavkaz-uzel.eu&site=korrespondent.net&site=krym.r.com&site=meduza.io&site=memohrc.org&site=moscowtimes.ru&site=navalny.com&site=newtimes.ru&site=novayagazeta.ru&site=ovd.info&site=paperpaper.ru&site=polit.ru&site=proekt.media&site=prostovpn.org&site=radiosvoboda.org&site=semnasem.org&site=svoboda.org&site=tayga.info&site=the-village.ru&site=theins.ru&site=thetruestory.news&site=tvrain.ru&site=unian.net&site=verstka.media&site=vot-tak.tv&site=zona.media",
    "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Categories/news.lst"
]
v2fly = ["category-media-ru"]

[groups.Pirate-Streaming-Services]
include = [
    "hdrezka", "kinovod", "kinopub", "kinobase",
    "filmix", "doramy-club", "lordfilm"
]
