name: Domains Automation

on:
  schedule:
    - cron: '0 10 * * *'
  push:
    paths:
      - 'data/**'
      - 'scripts/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      go-ready: ${{ steps.setup-go.outputs.ready }}
      py-ready: ${{ steps.setup-python.outputs.ready }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Go
        id: setup-go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: Install Go dependencies
        run: go mod download
      
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

  parse-domains:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: Run parsing-domains
        run: go run scripts/parsing-domains.go
      
      - name: Run process-domains
        run: go run scripts/process-domains.go
      
      - name: Commit and push domains changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/domains/*
          git commit -m "Update domains lists" || echo "No changes"
          git push

  parse-subnets:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: Run parsing-subnets
        run: go run scripts/parsing-subnets.go
      
      - name: Commit and push CIDR changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/CIDRs/*
          git commit -m "Update CIDR lists" || echo "No changes"
          git push

  generate-configs:
    needs: [parse-domains, parse-subnets, setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Generate all configs
        run: |
          python scripts/generate-srs.py
          python scripts/generate-routing-config.py
          python scripts/generate-sing-box-rules.py
      
      - name: Commit and push all generated configs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/rulesets/*
          git commit -m "Update all generated configs (SRS, routing, sing-box)" || echo "No changes"
          git push
